#!/bin/bash
bench_list=(
"b19"
#"vga_lcd"
#"mgc_edit_dist" 
#"mgc_matrix_mult" 
#"netcard"
#"leon2" 
#"leon3mp" 
)

script_list=(
"resyn"
"resyn2"
#"resyn2a"
"resyn3"
"compress"
"compress2"
#"resyn2rs"
#"compress2rs"
#"recadd3"
)

placer_list=(
"Capo"
"NTUPlace3"
"ComPLx"
#"mPL5"
#"mPL6"
)

router_list=(
"NCTUgr"
"FastRoute"
)

fp_dir="../200_floorplanning"
place_dir="../300_placement"
gr_bench_dir="../500_gr_bench_gen"

for bench in "${bench_list[@]}"
do
    for script in "${script_list[@]}"
    do
        for placer in "${placer_list[@]}"
        do
            for router in "${router_list[@]}"
            do
                base_name=${bench}_${script}_${placer}
                out_name=${base_name}_${router}

                # Output directory
                out_dir="gr_${out_name}"
                bookshelf_out_dir="bookshelf-${out_name}"

                # Plotting
                solution_pl=${place_dir}/${base_name}
                cmd="../utils/510_dac2012_evaluate_solution.pl -p ${out_dir}/${bookshelf_out_dir}/${bench}.aux ${place_dir}/${base_name}/${bench}_solution.pl ${out_dir}/$out_name"
                echo "Running: $cmd"
                $cmd | tee ${out_name}.dac2012_eval
                echo ""
                echo "Done."
                gnuplot ${bench}.Max_H.congestion.plt
                gnuplot ${bench}.Max_V.congestion.plt

                mv ${bench}* ${out_dir}
            done
        done
    done
done
