#!bin/bash
bench_list=("b19")
script_list=("resyn")
max_fo=16
placer_list=("NTUPlace3")
target_density=90
run_gs=false
sizer="USizer"
router_list=("NCTUgr")
tile_size=80
num_layer=8
adjustment=50
safety=90
